# -*- coding: utf-8 -*-
"""API_Flask_Desafio_COLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqpcg--kSIx_oy7y1dEma0kfU9aIeTsj
"""

!pip show flask
!pip show flask-ngrok

"""Instalação do flask-ngrok:

Reinstalar a Biblioteca: Adicione uma célula e execute o comando de instalação novamente:
"""

!pip install flask-ngrok

"""Verificar a Instalação:

Adicione outra célula para verificar se a instalação foi bem-sucedida:
"""

!pip show flask-ngrok

"""Implementação da API com Flask

    Importar Bibliotecas e Configurar Flask:
        Crie uma nova célula e adicione o seguinte código:
"""

from flask import Flask, jsonify
from flask_ngrok import run_with_ngrok
import pandas as pd

app = Flask(__name__)
run_with_ngrok(app)  # Inicia o ngrok quando a app for executada

"""A mensagem de erro indica que o módulo flask_ngrok não foi encontrado, apesar de termos instalado a biblioteca. Isso pode ocorrer por vários motivos, como problemas com a instalação do pacote ou conflitos de dependências.
Soluções para Resolver o Erro:

    Reinstalar o Pacote:
        Tente reinstalar o flask-ngrok novamente:
"""

!pip uninstall flask-ngrok -y
!pip install flask-ngrok

"""Confirmando a Instalação e Importação

    Primeiro, reinstale as bibliotecas conforme indicado acima.
    Verifique se o flask-ngrok está instalado e acessível:
"""

!pip show flask-ngrok

"""Implementação da API com Flask

    Importar Bibliotecas e Configurar Flask:
        Crie uma nova célula e adicione o seguinte código:
"""

from flask import Flask, jsonify
from flask_ngrok import run_with_ngrok
import pandas as pd

app = Flask(__name__)
run_with_ngrok(app)  # Inicia o ngrok quando a app for executada

"""Definir as Rotas da API:

    Adicione as rotas conforme descrito:
"""

@app.route("/")
def home():
    return "Hello, World!"

@app.route("/data")
def get_data():
    # Dados da planilha convertidos para JSON (exemplo)
    data = [
        {"Number": 1, "Name": "Mahesh", "Age": 25, "City": "Bangalore", "Country": "India"},
        {"Number": 2, "Name": "Alex", "Age": 26, "City": "London", "Country": "UK"},
        {"Number": 3, "Name": "David", "Age": 27, "City": "San Francisco", "Country": "USA"},
        {"Number": 4, "Name": "John", "Age": 28, "City": "Toronto", "Country": "Canada"},
        {"Number": 5, "Name": "Chris", "Age": 29, "City": "Paris", "Country": "France"}
    ]
    return jsonify(data)

"""Executar a Aplicação:

    Adicione o código para executar a aplicação:
"""

if __name__ == "__main__":
    app.run()

"""O erro que você está encontrando parece estar relacionado a problemas de conexão com o ngrok. Pode ser que a conexão com o servidor ngrok esteja falhando ou que o ngrok esteja bloqueado no ambiente Colab.

Vamos tentar alguns passos alternativos para contornar esse problema.
Passo Alternativo: Executar Flask Localmente sem ngrok

    Rodar a Aplicação Flask Localmente:
        Vamos configurar a aplicação Flask para rodar localmente sem usar o ngrok. Isso significa que você poderá acessar a aplicação apenas localmente dentro do ambiente Colab.

    Código para Executar Flask Localmente:
        Use o seguinte código para configurar e executar a aplicação Flask:
"""

from flask import Flask, jsonify
import pandas as pd

app = Flask(__name__)

@app.route("/")
def home():
    return "Hello, World!"

@app.route("/data")
def get_data():
    # Exemplo de dados da planilha convertidos para JSON
    data = [
        {"Number": 1, "Name": "Mahesh", "Age": 25, "City": "Bangalore", "Country": "India"},
        {"Number": 2, "Name": "Alex", "Age": 26, "City": "London", "Country": "UK"},
        {"Number": 3, "Name": "David", "Age": 27, "City": "San Francisco", "Country": "USA"},
        {"Number": 4, "Name": "John", "Age": 28, "City": "Toronto", "Country": "Canada"},
        {"Number": 5, "Name": "Chris", "Age": 29, "City": "Paris", "Country": "France"}
    ]
    return jsonify(data)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)

from flask import Flask, jsonify
from flask_ngrok import run_with_ngrok
import pandas as pd

app = Flask(__name__)
run_with_ngrok(app)  # Inicia o ngrok quando a app for executada

@app.route("/")
def home():
    return "Hello, World!"

@app.route("/data")
def get_data():
    data = [
        {"Number": 1, "Name": "Mahesh", "Age": 25, "City": "Bangalore", "Country": "India"},
        {"Number": 2, "Name": "Alex", "Age": 26, "City": "London", "Country": "UK"},
        {"Number": 3, "Name": "David", "Age": 27, "City": "San Francisco", "Country": "USA"},
        {"Number": 4, "Name": "John", "Age": 28, "City": "Toronto", "Country": "Canada"},
        {"Number": 5, "Name": "Chris", "Age": 29, "City": "Paris", "Country": "France"}
    ]
    return jsonify(data)

if __name__ == "__main__":
    app.run()

!pip install pyngrok

from flask import Flask, jsonify
from pyngrok import ngrok
import pandas as pd

app = Flask(__name__)

@app.route("/")
def home():
    return "Hello, World!"

@app.route("/data")
def get_data():
    data = [
        {"Number": 1, "Name": "Mahesh", "Age": 25, "City": "Bangalore", "Country": "India"},
        {"Number": 2, "Name": "Alex", "Age": 26, "City": "London", "Country": "UK"},
        {"Number": 3, "Name": "David", "Age": 27, "City": "San Francisco", "Country": "USA"},
        {"Number": 4, "Name": "John", "Age": 28, "City": "Toronto", "Country": "Canada"},
        {"Number": 5, "Name": "Chris", "Age": 29, "City": "Paris", "Country": "France"}
    ]
    return jsonify(data)

if __name__ == "__main__":
    public_url = ngrok.connect(5000)
    print(" * ngrok URL:", public_url)
    app.run()

!ngrok authtoken 2iLFDA................

from flask import Flask, jsonify
from pyngrok import ngrok
import pandas as pd

app = Flask(__name__)

@app.route("/")
def home():
    return "Hello, World!"

@app.route("/data")
def get_data():
    data = [
        {"Number": 1, "Name": "Mahesh", "Age": 25, "City": "Bangalore", "Country": "India"},
        {"Number": 2, "Name": "Alex", "Age": 26, "City": "London", "Country": "UK"},
        {"Number": 3, "Name": "David", "Age": 27, "City": "San Francisco", "Country": "USA"},
        {"Number": 4, "Name": "John", "Age": 28, "City": "Toronto", "Country": "Canada"},
        {"Number": 5, "Name": "Chris", "Age": 29, "City": "Paris", "Country": "France"}
    ]
    return jsonify(data)

if __name__ == "__main__":
    public_url = ngrok.connect(5000)
    print(" * ngrok URL:", public_url)
    app.run()